apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: "2.20.4"
    chart: external-dns

  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
