---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitops-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitops-agent
subjects:
  - kind: ServiceAccount
    name: gitops-agent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-agent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gitops-agent
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gitops-agent
    spec:
      containers:
        - command:
            - gitops
            - /tmp/git/repo
            - --path
            - ch06/simple-blue-green
            - --namespaced
          image: argoproj/gitops-agent:latest
          name: gitops-agent
          volumeMounts:
            - mountPath: /tmp/git
              name: git
        - args:
            - --webhook-url
            - http://localhost:9001/api/v1/sync
            - --dest
            - repo
          env:
            - name: GIT_SYNC_REPO
              value: https://github.com/PacktPublishing/ArgoCD-in-Practice
          image: k8s.gcr.io/git-sync:v3.1.6
          name: git-sync
          volumeMounts:
            - mountPath: /tmp/git
              name: git
      serviceAccountName: gitops-agent
      resources:
        limits:
          cpu: "1"
          memory: "128Mi"
        requests:
          cpu: "0.5"
          memory: "128Mi"
      volumes:
        - emptyDir: {}
          name: git
